#ifndef SHADERVOLUMES_H
#define SHADERVOLUMES_H

#define UINT_SLOT_ALBEDO 0
#define UINT_SLOT_NORMAL 1

#define VOLUME_SLOT_ALBEDO          0
#define VOLUME_SLOT_NORMAL          1
#define VOLUME_SLOT_RADIANCE        2
#define VOLUME_SLOT_RADIANCE_SMOOTH 3
#define VOLUME_SLOT_CASCADE         4
#define VOLUME_SLOT_IRRADIANCE      10
#define VOLUME_SLOT_SKY_OCCLUSION         16
#define VOLUME_SLOT_SKY_OCCLUSION_SCRATCH 17
#define VOLUME_SLOT_SCREEN_GI             18
#define VOLUME_SLOT_HANDOFF               24
#define VOLUME_SLOT_SCREEN_META           25

#define LIGHT_DIRECTIONS 6
#define LIGHT_GI_STRENGTH  1.0
#define LIGHT_OCCLUSION_STRENGTH 1.0
#define LIGHT_SKY_STRENGTH 1.0
#define LIGHT_BOUNCE_STRENGTH 0.95
#define LIGHT_BLEND           0.25

#define RC_CASCADE_COUNT  6
#define RC_PROBE_SIZE     64
#define RC_DIR_RES        4
#define RC_TILE_SIZE      (RC_PROBE_SIZE * RC_DIR_RES)
#define RC_BASE_STEPS     4
#define RC_GROUP_SIZE     8
#define RC_INTERVAL_SCALE 2.0f
#define RC_EXTINCTION     24.0f
#define RC_INV_PI         0.31830989
#define RC_PROBE_SOLID    0.5
#define RC_SUN_STEPS      96
#define RC_SUN_FRINGE     0.3

#define RC_SCREEN_TILE    4
#define RC_SCREEN_HANDOFF 2
#define RC_SCREEN_DIR_RES (RC_DIR_RES << (RC_SCREEN_HANDOFF - 1))
#define RC_IRRADIANCE_SIZE (RC_PROBE_SIZE >> RC_SCREEN_HANDOFF)
#define RC_SCREEN_GROUP 8
#define RC_SCREEN_NORMAL_TAP 2
#define RC_SCREEN_MAX_X 960
#define RC_SCREEN_MAX_Y 540

#define VOLUME_GROUP_SIZE 4
#define VOXEL_GROUP_SIZE  64

#define VOLUME_GRID_SIZE    128
#define LIGHT_GRID_SIZE     128
#define VOLUME_WORLD_EXTENT 6.0f

#define VOLUME_MODE_SLICE  0
#define VOLUME_MODE_COLUMN 1
#define VOLUME_MODE_CAMERA 2
#define VOLUME_MODE_LIGHT  3

#define VOLUME_MARCH_STEPS 512

#endif
