#ifndef SHADERHEAP_H
#define SHADERHEAP_H

#define SET_GLOBAL 0

#define BINDING_TEXTURES 0
#define BINDING_SAMPLER  1
#define BINDING_CUBEMAPS 2
#define BINDING_COUNT    3

#define MAX_TEXTURES 32
#define MAX_CUBEMAPS 4

#define MAX_MATERIALS 64

#define TEXTURE_NONE 0xFFFFFFFF

#define TEXTURE_SLOT_SCENE MAX_TEXTURES
#define TEXTURE_SLOT_POST  (TEXTURE_SLOT_SCENE + 1)
#define TEXTURE_HEAP_SIZE (TEXTURE_SLOT_POST + 1)

#define VERTEX_STRIDE    44
#define MATERIAL_STRIDE  32
#define RECT_PARAMS_STRIDE 64

#endif
