#ifndef SHADERVOLUMES_H
#define SHADERVOLUMES_H

#define LIGHT_DIRECTIONS 6
#define LIGHT_GI_STRENGTH  1.0
#define LIGHT_OCCLUSION_STRENGTH 1.0
#define LIGHT_SKY_STRENGTH 1.0
#define LIGHT_BOUNCE_STRENGTH 0.95
#define LIGHT_BLEND           0.25

#define RC_CASCADE_COUNT  6
#define RC_PROBE_SIZE     64u
#define RC_DIR_RES        4u
#define RC_TILE_SIZE      (RC_PROBE_SIZE * RC_DIR_RES)
#define RC_BASE_STEPS     4u
#define RC_GROUP_SIZE     8
#define RC_INTERVAL_SCALE 2.0f
#define RC_EXTINCTION     24.0f
#define RC_INV_PI         0.31830989
#define RC_PROBE_SOLID    0.5
#define RC_SUN_STEPS      96
#define RC_SUN_FRINGE     0.3

#define RC_SCREEN_TILE    4
#define RC_SCREEN_HANDOFF 2
#define RC_SCREEN_DIR_RES (RC_DIR_RES << (RC_SCREEN_HANDOFF - 1))
#define RC_IRRADIANCE_SIZE (RC_PROBE_SIZE >> RC_SCREEN_HANDOFF)
#define RC_SCREEN_GROUP 8
#define RC_SCREEN_NORMAL_TAP 2
#define RC_SCREEN_MAX_X 960u
#define RC_SCREEN_MAX_Y 540u

#define RC_CASCADE_PROBE_SIZE(cascade) (RC_PROBE_SIZE >> (cascade))
#define RC_CASCADE_DIR_RES(cascade)    (RC_DIR_RES << (cascade))
#define RC_CASCADE_STEPS(cascade)      (RC_BASE_STEPS << (cascade))

#define RC_HANDOFF_CASCADE    (RC_SCREEN_HANDOFF + 1)
#define RC_HANDOFF_PROBE_SIZE RC_CASCADE_PROBE_SIZE(RC_HANDOFF_CASCADE)
#define RC_HANDOFF_TILE_SIZE  (RC_HANDOFF_PROBE_SIZE * RC_SCREEN_DIR_RES)

#define RC_SCREEN_TILES(pixels)    (((pixels) + RC_SCREEN_TILE - 1) / RC_SCREEN_TILE)
#define RC_SCREEN_PROBES_X(width)  (RC_SCREEN_TILES(width)  > RC_SCREEN_MAX_X ? RC_SCREEN_MAX_X : RC_SCREEN_TILES(width))
#define RC_SCREEN_PROBES_Y(height) (RC_SCREEN_TILES(height) > RC_SCREEN_MAX_Y ? RC_SCREEN_MAX_Y : RC_SCREEN_TILES(height))

#define UINT_SLOT_ALBEDO 0
#define UINT_SLOT_NORMAL 1
#define UINT_SLOT_COUNT  2

#define VOLUME_SLOT_ALBEDO                0
#define VOLUME_SLOT_NORMAL                1
#define VOLUME_SLOT_SKY_OCCLUSION         2
#define VOLUME_SLOT_SKY_OCCLUSION_SCRATCH 3
#define VOLUME_SLOT_RADIANCE              4
#define VOLUME_SLOT_RADIANCE_SMOOTH       5
#define VOLUME_SLOT_CASCADE               6
#define VOLUME_SLOT_IRRADIANCE            (VOLUME_SLOT_CASCADE     + RC_CASCADE_COUNT)
#define VOLUME_SLOT_SCREEN_GI             (VOLUME_SLOT_IRRADIANCE  + LIGHT_DIRECTIONS)
#define VOLUME_SLOT_HANDOFF               (VOLUME_SLOT_SCREEN_GI   + LIGHT_DIRECTIONS)
#define VOLUME_SLOT_SCREEN_META           (VOLUME_SLOT_HANDOFF     + 1)
#define VOLUME_SLOT_COUNT                 (VOLUME_SLOT_SCREEN_META + 1)

#define VOLUME_GROUP_SIZE 4
#define VOXEL_GROUP_SIZE  64

#define VOLUME_GRID_SIZE    128
#define LIGHT_GRID_SIZE     128
#define VOLUME_WORLD_EXTENT 6.0f

#define VOLUME_MODE_SLICE  0
#define VOLUME_MODE_COLUMN 1
#define VOLUME_MODE_CAMERA 2
#define VOLUME_MODE_LIGHT  3

#define VOLUME_MARCH_STEPS 512

#endif
