#ifndef SHADERHEAP_H
#define SHADERHEAP_H

#define SET_GLOBAL 0

#define BINDING_TEXTURES        0
#define BINDING_SAMPLER         1
#define BINDING_CUBEMAPS        2
#define BINDING_VOLUMES         3
#define BINDING_STORAGE_VOLUMES 4
#define BINDING_UINT_VOLUMES    5
#define BINDING_VOLUME_SAMPLER  6

#define MAX_TEXTURES  32
#define MAX_CUBEMAPS  4
#define MAX_VOLUMES      32
#define MAX_UINT_VOLUMES 2

#define MAX_MATERIALS 64

#define TEXTURE_NONE 0xFFFFFFFF

#define TEXTURE_SLOT_SCENE MAX_TEXTURES
#define TEXTURE_SLOT_POST  (TEXTURE_SLOT_SCENE + 1)
#define TEXTURE_SLOT_DEPTH (TEXTURE_SLOT_POST + 1)
#define TEXTURE_HEAP_SIZE  (TEXTURE_SLOT_DEPTH + 1)

#define VERTEX_STRIDE    44
#define MATERIAL_STRIDE  32
#define RECT_PARAMS_STRIDE 64

#endif
